#pragma once
// ============================================================
// WebHTML_Config.h — Page Configuration HTML
// ============================================================

#define WEB_CONFIG_HTML R"HTML(
<!-- ══ PAGE CONFIGURATION ════════════════════════════ -->
<div id="page-config" class="page">
  <div class="card" style="padding:24px">

    <div class="config-section">
      <h3>Noms des vannes</h3>
      <div class="form-grid" id="valve-names-grid">
        <!-- generated by JS -->
      </div>
    </div>

    <div class="config-section">
      <h3>WiFi</h3>
      <div class="config-row">
        <div>
          <label>SSID</label>
          <input type="text" id="cfg-ssid" placeholder="Freebox-XXXXXX"/>
        </div>
        <div>
          <label>Mot de passe</label>
          <input type="password" id="cfg-wpass" placeholder="••••••••"/>
        </div>
      </div>
    </div>

    <div class="config-section">
      <h3>LoRa</h3>
      <div class="config-row">
        <div>
          <label>Fréquence (MHz)</label>
          <input type="number" id="cfg-lfreq" step="0.1" min="433" max="928"/>
        </div>
        <div>
          <label>Puissance (dBm)</label>
          <input type="number" id="cfg-lpow" min="-3" max="20"/>
        </div>
      </div>
      <div class="config-row">
        <div>
          <label>Node ID</label>
          <input type="text" id="cfg-nodeid" placeholder="IRRIGATION01"/>
        </div>
        <div></div>
      </div>
    </div>

    <div class="config-section">
      <h3>Mode d'irrigation</h3>
      <div class="toggle-row">
        <label>Parallèle <span style="color:var(--text-muted)">— toutes les vannes peuvent être ouvertes simultanément</span></label>
        <div class="toggle">
          <input type="checkbox" id="cfg-seq">
          <span class="toggle-slider"></span>
        </div>
        <label>Séquentiel <span style="color:var(--text-muted)">— une seule vanne ouverte à la fois</span></label>
      </div>
      <div class="config-row">
        <div>
          <label>Durée max par vanne (secondes)</label>
          <input type="number" id="cfg-maxopen" min="1" max="86400"/>
        </div>
        <div>
          <label>Durée forçage manuel (secondes)</label>
          <input type="number" id="cfg-forcedu" min="1" max="86400"/>
        </div>
      </div>
    </div>

    <div class="config-section">
      <h3>MQTT / Home Assistant</h3>
      <div class="toggle-row">
        <label>Activer MQTT</label>
        <div class="toggle">
          <input type="checkbox" id="cfg-mqena">
          <span class="toggle-slider"></span>
        </div>
      </div>
      <div class="config-row">
        <div>
          <label>Serveur</label>
          <input type="text" id="cfg-mqhost" placeholder="192.168.1.100"/>
        </div>
        <div>
          <label>Port</label>
          <input type="number" id="cfg-mqport" min="1" max="65535"/>
        </div>
      </div>
      <div class="config-row">
        <div>
          <label>Utilisateur</label>
          <input type="text" id="cfg-mquser"/>
        </div>
        <div>
          <label>Mot de passe</label>
          <input type="password" id="cfg-mqpass"/>
        </div>
      </div>
      <div class="config-row">
        <div>
          <label>Prefix discovery</label>
          <input type="text" id="cfg-mqprefix" placeholder="homeassistant"/>
        </div>
        <div>
          <label>Client ID</label>
          <input type="text" id="cfg-mqid" placeholder="irrpro_hs3"/>
        </div>
      </div>
    </div>

    <div class="config-section">
      <h3>État NVS</h3>
      <div class="nvs-gauge-wrap">
        <div class="nvs-gauge-label">
          <span>Partition NVS</span>
          <span class="pct" id="nvs-pct">—%</span>
        </div>
        <div class="nvs-gauge">
          <div class="nvs-gauge-fill" id="nvs-fill" style="width:0%"></div>
        </div>
        <div class="nvs-gauge-detail" id="nvs-detail">—</div>
      </div>
      <div style="margin-top:12px;font-size:.8rem;color:var(--text-muted">
        La NVS stocke la configuration, les programmes et les compteurs.
        Si le remplissage dépasse 90%, sauvegarder peut échouer.
      </div>
    </div>

    <div class="config-section">
      <h3>Consommation par vanne</h3>
      <div style="overflow-x:auto">
        <table class="tbl">
          <thead>
            <tr>
              <th>Vanne</th>
              <th>Nom</th>
              <th>Aujourd'hui</th>
              <th>Total</th>
              <th>Détail 14 derniers jours</th>
            </tr>
          </thead>
          <tbody id="cons-body">
            <tr><td colspan="5" style="text-align:center;color:var(--text-muted);padding:24px">Chargement…</td></tr>
          </tbody>
        </table>
      </div>
      <div style="margin-top:16px;display:flex;gap:10px;flex-wrap:wrap">
        <button class="btn btn-red" onclick="resetPulse()">🔄 Remettre à zéro tous les compteurs</button>
        <button class="btn btn-ghost" onclick="refreshConsumption()">↻ Actualiser</button>
      </div>
    </div>

    <div style="margin-top:24px;display:flex;gap:12px;flex-wrap:wrap">
      <button class="btn btn-blue" onclick="saveConfig()">💾 Enregistrer</button>
      <button class="btn btn-ghost" onclick="loadConfig()">↺ Recharger</button>
      <button class="btn btn-red" onclick="closeAll()" style="margin-left:auto">🚪 Fermer toutes les vannes</button>
    </div>
  </div>
</div>
)HTML";