#pragma once
// ============================================================
// WebHTML_EOS.h — Page Entrées/Sorties HTML
// ============================================================

#define WEB_EOS_HTML R"HTML(
<!-- ══ PAGE ENTRÉES/SORTIES ════════════════════════════ -->
<div id="page-io" class="page">
  <div class="card">
    <div class="card-header">
      <h2>État des Entrées/Sorties</h2>
      <button class="btn btn-ghost btn-sm" onclick="requestStatus()">Actualiser</button>
    </div>
    <div style="padding:20px;overflow-x:auto">
      <table class="tbl">
        <thead>
          <tr>
            <th></th>
            <th>PD0</th>
            <th>PD1</th>
            <th>PD2</th>
            <th>PD3</th>
            <th>PD4</th>
            <th>PD5</th>
            <th>PD6</th>
            <th>PD7</th>
          </tr>
        </thead>
        <tbody id="io-body">
          <!-- generated by JS -->
        </tbody>
      </table>
      <div style="margin-top:20px;font-size:.85rem;color:var(--text-muted">
        <strong>Légende :</strong><br>
        <strong>PD</strong> = sorties vannes (0-4) + LED visu (5) + sorties auxiliaires (6-7)<br>
        <strong>PA</strong> = LED visu (0-4)<br>
        <strong>In</strong> = entrées forçage manuel (0-7)<br>
        <br>
        <strong>Broche PB7 (In7)</strong> = compteur d'impulsions (débitmètre)<br>
        <strong>Broche PA0-4</strong> = LED visu état vanne (1 = ouverte)<br>
        <strong>Broche PD5</strong> = LED visu état vanne (5)<br>
        <strong>Broche PD6-7</strong> = sorties auxiliaires (relais, etc.)<br>
      </div>
    </div>
  </div>
</div>
)HTML";