#pragma once
// ============================================================
// WebHTML_Calendrier.h — Page Calendrier HTML
// ============================================================

// Inclusion des fichiers JS séparés
#include "WebJS_Core.h"
#include "WebJS_Dashboard.h"
#include "WebJS_Programmes.h"
#include "WebJS_Calendrier.h"
#include "WebJS_Calibration.h"
#include "WebJS_Config.h"
#include "WebJS_Journal.h"


#define WEB_CALENDRIER_HTML R"HTML(
<!-- ══ PAGE CALENDRIER ═════════════════════════════════ -->
<div id="page-calendrier" class="page">
  <div class="card">
    <div class="card-header">
      <h2>Calendrier des arrosages</h2>
    </div>
    <div style="padding:20px">
      <div class="cal-nav">
        <button class="btn btn-ghost" onclick="calPrevMonth()">&lt; Mois précédent</button>
        <h2 id="cal-month-year">—</h2>
        <button class="btn btn-ghost" onclick="calNextMonth()">Mois suivant &gt;</button>
      </div>
      <div class="cal-grid" id="cal-grid">
        <!-- generated by JS -->
      </div>
    </div>
  </div>
</div>
)HTML";